spring:
  application:    name: gateway-server
  cloud:    gateway:      discovery:        locator:          enabled: true
          lower-case-service-id: true
  config:    import: optional:configserver:http://localhost:8888
  
server:  port: 8765

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
  instance:    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'