spring:
  application:
    name: config-sever
  cloud:
    config:
      server:
        git:
          uri : https://github.com/repotec/ecommerce-store/tree/master/config-server/src/main/resources/shared
      
  profiles:
     active: dev
 
server:
  port: 8888
  
  

  
