spring:
  application:
    name: config-sever
  cloud:    config:      server:        git:          uri: https://github.com/repotec/ecommerce-store/blob/master/config-server/src/main/resources/shared
 
server:
  port: 8888
  
  
  
  
  

  
